language: ruby
deploy:
  provider: rubygems
  api_key:
    secure: LAM8qxTQa6oxzKiQpWrqRlcE1czmGFj16NSj1FVgZYJLZIfXKdvSpth+DfuCk8mxG1tvDXa3ckfERrzexG3lYGNPGyZH2sjnyt900Evd3Bn8vhv0LXE7cEZb3x/uJ3RHRvKpEDnMsy4gqoVByDLWXWnI9Q/8B4AtzFeTVsTr48g=
  gem: knife-changelog
  on:
    tags: true
    repo: kamaradclimber/knife-changelog
sudo: false # use docker based infra
